# Generated by Django 3.0.3 on 2021-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(blank=True, max_length=255)),
                ('Fid', models.CharField(blank=True, max_length=255)),
                ('Filename', models.CharField(blank=True, max_length=500)),
                ('Password', models.CharField(blank=True, max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FileDetails',
            },
        ),
    ]
