# Generated by Django 3.0.3 on 2021-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0002_filedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedetails',
            name='Fid',
        ),
        migrations.RemoveField(
            model_name='filedetails',
            name='Uid',
        ),
        migrations.AddField(
            model_name='filedetails',
            name='AES',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='DES',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='FERNET',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='ReceiverId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='SenderId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
