# Generated by Django 3.0.3 on 2021-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0003_auto_20210218_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='AES',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='DES',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='FERNET',
            field=models.TimeField(default=None),
        ),
    ]
