# Generated by Django 3.0.3 on 2021-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0004_auto_20210218_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='Date',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
