# Generated by Django 3.0.3 on 2021-02-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0005_auto_20210218_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedetails',
            name='Date',
        ),
    ]
