# Generated by Django 3.0.3 on 2021-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0006_remove_filedetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='AES',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='DES',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='FERNET',
            field=models.TextField(default=None),
        ),
    ]
