# Generated by Django 3.2.12 on 2022-03-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0007_auto_20210218_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedetails',
            old_name='FERNET',
            new_name='ARC2',
        ),
    ]
