# Generated by Django 3.2.12 on 2022-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0008_rename_fernet_filedetails_arc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='ARC2IV',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='ARC2key',
            field=models.TextField(default=None),
        ),
    ]
