# Generated by Django 3.2.12 on 2022-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0009_auto_20220324_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='ARC2IV',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='ARC2key',
            field=models.BinaryField(),
        ),
    ]
