# Generated by Django 3.2.12 on 2022-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSecureHybrid', '0010_auto_20220324_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='Image',
            field=models.ImageField(default=None, upload_to='media/img/images/Encrypted/'),
        ),
    ]
